<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>blif</string>
    <key>fileTypes</key>
    <array>
        <string>blif</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#keywords_generic</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords_lgate</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords_fsm</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#subckt_parameters</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords_generic</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.model\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.inputs\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.outputs\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.end\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.subckt\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.search\b</string>
          </dict>
        </array>
      </dict>
      <key>keywords_lgate</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.exdc\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.names\b</string>
          </dict>
        </array>
      </dict>
      <key>keywords_fsm</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.start_kiss\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.i\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.o\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.s\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.p\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.r\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.end_kiss\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.code\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.blif</string>
            <key>match</key>
            <string>^\.latch\b</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>name</key>
        <string>comment.line</string>
        <key>match</key>
        <string>#.*</string>
      </dict>
      <key>subckt_parameters</key>
      <dict>
        <key>name</key>
        <string>variable.parameter</string>
        <key>match</key>
        <string>\s(\S+)=(\S+)</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.blif</string>
  </dict>
</plist>